### ISSUE TITLE
Windows does not recognize the "PORT=3006" command in package.json

### ISSUE THREAD

**Issue by murezzda** [bbc/react-transcript-editor#100]
**Describe the bug**
If the project is currently startet under Windows 7, the following error occurs (error is in german because of OS language):

```
Der Befehl "PORT" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bbc/react-transcript-editor@0.2.12 start: "PORT=3006 react-scripts start"
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @bbc/react-transcript-editor@0.2.12 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! [path_to_log_file]
```

**To Reproduce**
1. Use Windows as OS.
2. Run 'npm start' in the project folder.

**Additional context**
Using `set PORT=3006 && react-scripts start` instead of  `PORT=3006 react-scripts start` in `package.json` fixes the problem for Windows, but might not work on UNIX Systems. Alternatively, environment variables could be stored in a `.env` file instead in `package.json`.

See also the following discussion: [https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project](https://stackoverflow.com/questions/40714583/how-to-specify-a-port-to-run-a-create-react-app-based-project)

**Comment by pietrop** [comment]
Thanks @murezzda , a quick fix I can think of is to go back to the default `3000` port, would that work for you?
_and spare any fiddly cross platform configuration at this stage_

**Comment by murezzda** [comment]
That would also be ok for me. Thanks!

**Comment by pietrop** [comment]
addressed in PR https://github.com/bbc/react-transcript-editor/pull/101

**Comment by pietrop** [comment]
Just making a note, if we ever need to revisit this, I found that [`cross-env `](https://www.npmjs.com/package/cross-env) (mentioned in [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/))  could be used for this.

> Run scripts that set and use environment variables across platforms

>Most Windows command prompts will choke when you set environment variables with NODE_ENV=production like that. (The exception is Bash on Windows, which uses native Bash.) Similarly, there's a difference in how windows and POSIX commands utilize environment variables. With POSIX, you use: $ENV_VAR and on windows you use %ENV_VAR%.

>cross-env makes it so you can have a single command without worrying about setting or using the environment variable properly for the platform. Just set it like you would if it's running on a POSIX system, and cross-env will take care of setting it properly.

[see their README for more info](https://github.com/kentcdodds/cross-env#readme)
