### ISSUE TITLE
Start video at text-cursor

### ISSUE THREAD

**Issue by murezzda** [bbc/react-transcript-editor#106]
**Is your feature request related to a problem? Please describe.**
In conjunction with #97, it would be great if the player can be started from the current word at the cursor position. This would allow for rapid navigation inside the video via keyboard.

**Describe the solution you'd like**
If the user starts the video via the `alt+k` shortcut, the video starts from the current cursor position instead of the current video position.

**Additional context**
As this feature alters the behaviour of the `alt+k` shortcut significantly, it might be good to put an option in the option menu to enable/disable this behaviour. Alternatively, another shortcut could be introduced for this feature, but I think this might increase the complexity of the application too much.

**Comment by pietrop** [comment]
Thanks @murezzda since we closed https://github.com/bbc/react-transcript-editor/issues/97 and parked it for now, closing this one as well. We are looking to consolidate the component before adding new feature, but happy to revisit at a later stage
