### ISSUE TITLE
Total playtime on display is double of actual total playtime

### ISSUE THREAD

**Issue by murezzda** [bbc/react-transcript-editor#132]
**Describe the bug**
The total playtime displayed in the player shows double the value of the actual playtime of the file.

![bug_length_of_file](https://user-images.githubusercontent.com/47388020/55706590-dc4c1c80-59e1-11e9-8f53-32f579bb7d1d.png)

**Expected behavior**
The correct total playtime is shown.

**Comment by pietrop** [comment]
Nicely spotted, thanks @murezzda !

I think I found it, [it's `onLoadedDataGetDuration` in `TranscriptEditor/index.js`](https://github.com/bbc/react-transcript-editor/blob/master/src/lib/TranscriptEditor/index.js#L251)

```diff
  onLoadedDataGetDuration = e => {
    const currentDuration = e.target.duration;
    const currentDurationWithOffset =
      currentDuration + this.state.timecodeOffset;
    const durationInSeconds = secondsToTimecode(
-      currentDuration + currentDurationWithOffset
+     currentDurationWithOffset
    );

    this.setState({
      mediaDuration: durationInSeconds
    });
```

fixing in PR https://github.com/bbc/react-transcript-editor/pull/135
