### ISSUE TITLE
Adding interim timestamps and splitting when speakers change

### ISSUE THREAD

**Issue by actionableinsights** [bbc/react-transcript-editor#151]
**Is your feature request related to a problem? Please describe.**
When editing the transcript I find when one speaker interjects I cant easily add their Name plus a timestamp in between the main speaker. 

**Describe the solution you'd like**
Keyboard shortcut at speaker creates a new line with the timestamp where one can add the speaker name as normal.

**Describe alternatives you've considered**
None. Manual insertion of text works but not add new speaker.
**Additional context**

**Comment by pietrop** [comment]
Thanks for raising this issue @actionableinsights, 

At that moment if you hit `Enter` on the keyboard it creates a new paragraph, with timestamp and speaker name and default speaker name (taken from current paragraph). You can then click on the speaker to edit the speaker's name. See example below:

![enter-troubleshoot](https://user-images.githubusercontent.com/4661975/56838681-d033dc00-6876-11e9-913c-42bf1ba6d7b6.gif)

Let me know if this doesn't solve your problem, or if I have misunderstood your question?

**Comment by pietrop** [comment]
@actionableinsights closing this issue for now, but feel free to let me know if this didn't answer your question

**Comment by actionableinsights** [comment]
Dear Pietro

I believe that did the trick.
Thanks!

Coder V
