### ISSUE TITLE
Version 1.0.3 remains unpublished on npm

### ISSUE THREAD

**Issue by terite** [bbc/react-transcript-editor#161]
Not exactly a bug, more of a "deploy request"

**Describe the bug**
The version in master branch's package.json is `1.0.3`, however the latest published version is 1.0.2

**To Reproduce**
1. Go to https://www.npmjs.com/package/@bbc/react-transcript-editor
2. Observe 1.0.2 as published version

**Expected behavior**
Expect to see 1.0.3 as published version

**Comment by pietrop** [comment]
Thanks for flagging this @terite 
I've updated on npm, had to skip a version coz forgot to include the README in the npm folder.

So it's now version [`1.0.3`](https://www.npmjs.com/package/@bbc/react-transcript-editor)
