### ISSUE TITLE
How can i make transcript for  my  custom video in json format( bbc kaldi)

### ISSUE THREAD

**Issue by Dheeraj15515** [bbc/react-transcript-editor#162]
I want to get transcript data of my custom video same as sample data present in project. How can  i do it please help

**Comment by pietrop** [comment]
Hi @Dheeraj15515 
You will need to generate a transcription using a STT service. 

As of today component supports converting from these major STT services
- speechmatics
- AWS Transcribe
- IBM Watson 

BBC Kaldi is a BBC internal STT which unfortunately is not open source.

As a workaround you could use [autoedit.io]( http://autoedit.io) to generate your transcription json, with [one of the STT services supported by autoEdit](https://autoedit.gitbook.io/user-manual/setup-stt-apis) 
- pocketsphinx (free and open source - on mac)
- Genelt (free and open source - on mac)
- IBM Watson 
- AssemblyAi
- Speechmatics 

And then import the autoEdit json of the transcription into transcript editor for your demo.

Hope this helps, I think it might be good to understand a bit better what are you trying to do with this component? in case there's a more appropriate solution.

**Comment by Dheeraj15515** [comment]
Thank you so much for your valuable response.
Actually i am making a web application where i have to show transcript for my videos and this react tool is very suitable for it. but the problem is that how can make my transcript with timestamps

**Comment by Dheeraj15515** [comment]
And as i am student b..i want to do it free of cost

**Comment by pietrop** [comment]
Yeah, so autoEdit is open source so you can reuse some of that code if it helps. 

Less accurate, but this is a link to the [pocketsphinx](https://github.com/OpenNewsLabs/offline_speech_to_text) no wrapper used in autoEdit.

And also check out [Gentle STT for free/open source stt](https://lowerquality.com/gentle).

Closing this issue for now, but feel free to ask if you have any follow up questions
