### ISSUE TITLE
I have an application made in php . I want to use this tool in my application to show transcripts. 

### ISSUE THREAD

**Issue by Dheeraj15515** [bbc/react-transcript-editor#164]
I have an application made in php . I want to use this tool in my application to show transcripts. Can you please tell how can i embed this tool in my application. Is there any CDN or any example to do so?  I will be very thankful to you

**Comment by pietrop** [comment]
Hi @Dheeraj15515,
At the moment there's no CDN. The [demo app](https://github.com/bbc/react-transcript-editor/tree/master/demo) contains an example on how to use the component.

For using React in your php app, you'll have to look at the [React documentation](https://reactjs.org) - see [Add React to a Website](https://reactjs.org/docs/add-react-to-a-website.html)

Hope this helps
