### ISSUE TITLE
How can I customize styles?

### ISSUE THREAD

**Issue by booooooo7** [bbc/react-transcript-editor#165]
Hi. You are developing a wonderful tool. But I have one problem, I would like to change styles for some component. As I see you are using module.css, and there is no way to override styles for components. How can I do that? If there is no such possibility now, is it planned to add it in the future?

**Comment by pietrop** [comment]
Hi @booooooo7 
This is something we have been thinking about as a separate issue https://github.com/bbc/react-transcript-editor/issues/28.

Let me know if you are interested/and have the capacity to help out with this?

As a starting point it might be good to do an [ADR](https://github.com/bbc/react-transcript-editor#documentation) to capture some possible options to address this. Then after evaluating pros and cons, and deciding on one a PR would be welcome.

**Comment by pietrop** [comment]
Closing this issue in favour of https://github.com/bbc/react-transcript-editor/issues/28
