### ISSUE TITLE
CSS not showing up when using component -v1.2.0

### ISSUE THREAD

**Issue by pietrop** [bbc/react-transcript-editor#204]
**Describe the bug**

CSS not showing up when using component in another app

**To Reproduce**
1. Create an app with Create React App
2. install and initialise the component `@bbc/react-transcript-editor@1.2.0`
4. See error. no CSS 🤷‍♂ 🤦‍♂ 

**Expected behavior**

To have CSS working in the packaged component.

**Screenshots**

![Screenshot 2019-10-07 at 12 31 56](https://user-images.githubusercontent.com/4661975/66308492-2feee280-e8ff-11e9-9e30-ffd99c535f9b.png)

**Additional context**

Create React App doesn't come with `.scss`. 

`.scss` might need to be bundled into a `.css` file when packaging/distributing the component to make it more widely compatible?

Earlier webpack config before `.scss` introduction [`webpack.config.js`](https://github.com/bbc/react-transcript-editor/blob/e301db1167a67f95f1bfc5e4cb6b2f0d25d05592/webpack.config.js)

**Comment by emettely** [comment]
Apologies, it might be something I introduced when updating webpack config to build. See https://github.com/bbc/react-transcript-editor/tree/pr/204
