### ISSUE TITLE
Demo doesn't seem to support WAV files

### ISSUE THREAD

**Issue by brilhana** [bbc/react-transcript-editor#241]
Demo doesn't seem able to load and play local WAV files but works fine for MP3 and MP4.

Desktop:
 - OS: Windows
 - Browser Chrome
 - Version 84

**Comment by pietrop** [comment]
👋 @brilhana 
have you tried to double check if that wav file plays in chrome? Eg By dropping it into a new tab.

**Comment by brilhana** [comment]
Chrome won't play the file. The controls are visible but the file won't play but it sounds like bug on Chome's side: https://bugs.chromium.org/p/chromium/issues/detail?id=83323

**Comment by pietrop** [comment]
What about Firefox?

**Comment by brilhana** [comment]
Firefox won't load it.

**Comment by bevand10** [comment]
Do you happen to know the origin of your wav file - which system created it, how many channels in it, is it PCM audio or another encoder, sample rate etc?

If it’s possible to share the audio somewhere we might be able to help diagnose the reason it won’t load.

Also, the chrome bug report you linked to is quite old (it was for version 13, we’re up at version 80+ now).

**Comment by brilhana** [comment]
Unfortunately there's no way to look at the metadata for the WAV file so I'll close this issue. I converted the WAV to MP3 as a workaround.
