### ISSUE TITLE
Display time "moves" during time update

### ISSUE THREAD

**Issue by pietrop** [bbc/react-transcript-editor#73]
**Describe the bug**

**To Reproduce**

- Load a transcript and click play
- watch the display time

**Expected behavior**

expect it not to move

**Screenshots**

![bug-time-display](https://user-images.githubusercontent.com/4661975/51125711-24abd200-1819-11e9-8996-fc324e1ca6f2.gif)

**Additional context**

Might be a quick CSS fix?

**Comment by pietrop** [comment]
closing this, as CSS has moved on since, but can be reopened if anyone comes across it

**Comment by pietrop** [comment]
Added the component to an app with React bootstrap and seems like the bug is not gone?
Altho it doesn't show up in the demo app. 

![bug-rte](https://user-images.githubusercontent.com/4661975/54849712-f943d880-4cdc-11e9-982f-a7ef9c1c3651.gif)

**Comment by Gribbs** [comment]
I also see the same behavior when adding the component to a different App

**Comment by bevand10** [comment]
You need to use a monospace font to avoid movement.

**Comment by pietrop** [comment]
ok, thanks @Gribbs and @bevand10, so a fix could be to add a [`monospace`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) `font-family`font-family to `PlayerControls.module.css` such as 

```css
...
.currentTime {
   ...
  font-family: 'Lucida Console',  monospace;
}

.duration {
  ...
  font-family: 'Lucida Console',  monospace;
}
```
This 

<img width="783" alt="Screen Shot 2019-04-08 at 16 19 53" src="https://user-images.githubusercontent.com/4661975/55735907-2ea92f80-5a1a-11e9-93e3-4ef1e8cfa936.png">


Don't want to get into fonts and UI details, but I am not sure tho how this will work, for example when adding into a parent app where we have [BBC Reith fonts](https://www.bbc.co.uk/gel/articles/introducing-bbc-reith). Because of [css specificity rules](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) `currentTime` and `duration` might stick to `mono` and not pick up the Reith font, and might stand out as being of a different font.

Just thinking out loud if there's a quick fix for this (cc @jamesdools ).

**Comment by bevand10** [comment]
The point with timecode display is that is should *always* be monospace.

Even in a BBC scenario where Reith is used elsewhere, it should still be a monospace font otherwise it'll bounce around just as it does now - Reith does not have a monospace variant.

It's because, to avoid horizontal movement, the width of 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 and : must be identical.

**Comment by pietrop** [comment]
Awesome, thanks for clarifying that @bevand10 
closing this issue it has been addressed in the "monorepo refactor" branch https://github.com/bbc/react-transcript-editor/pull/130
