### ISSUE TITLE
alt+space keyboard shortcut for pause+play also adds a space

### ISSUE THREAD

**Issue by pietrop** [bbc/react-transcript-editor#77]
**Describe the bug**
alt+space is the current keyboard shortcut for pause+play.
when clicking alt+space if the cursor is in the text area it also adds a space

**To Reproduce**
1. Go to [https://bbc.github.io/react-transcript-editor/](https://bbc.github.io/react-transcript-editor/)
2. Click on `load demo`
3. click / add cursor to text editing area
4. click `alt`+`space`
4. See error: there's an extra space beeing added

**Expected behavior**
 if cursor  in text editor area not to add a space when using alt + space

**Screenshots**

![bug-alt-space-play-pause](https://user-images.githubusercontent.com/4661975/51255186-9f502b00-199a-11e9-8241-c79d80375088.gif)

**Desktop (please complete the following information):**
 - OS:  OSX
 - Browser: Chrome

**Additional context**
Might be linked to https://github.com/bbc/react-transcript-editor/issues/75 and https://github.com/bbc/react-transcript-editor/pull/76 as possible solution

**Comment by ranaharoni** [comment]
I'll have a look at it later on today.
FYI: The `alt`+`k` is also an issue as it prints an `§` character (right after the prompt)

**Comment by pietrop** [comment]
Thanks @ranaharoni , let me know what you think.
Is something to keep in mind when addressing https://github.com/bbc/react-transcript-editor/issues/78

**Comment by pietrop** [comment]
closing in favour of this issue https://github.com/bbc/react-transcript-editor/issues/78 and this PR https://github.com/bbc/react-transcript-editor/pull/79
