### ISSUE TITLE
Put focus on text when pause via shortcuts

### ISSUE THREAD

**Issue by murezzda** [bbc/react-transcript-editor#97]
**Is your feature request related to a problem? Please describe.**
If the player is stopped via keyboard shortcut, the focus will not be on the text and it is not possible to quickly edit the script only via shortcuts.

**Describe the solution you'd like**
Upon pausing the player via shortcuts, the curser will be set to the word corresponding to the current timestamp. This allows for a quick correction of false transcribed words.

**Describe alternatives you've considered**
The alternative is to rely on the autoscroll feature and manually move the focus after pausing.

**Additional context**
It would be great if the player was usable only via keyboard, as this would speed up the correction of the transcript.

**Comment by pietrop** [comment]
Sounds great, thanks for raising this @murezzda !

Good to keep an eye out on how this will also work with the [`scroll-sync`](https://github.com/bbc/react-transcript-editor/blob/master/docs/qa/3-settings.md#item-to-test-35-settings---scroll-sync---on) feature (that when enabled in settings, keeps the current text in view)

PR welcome, if you want to give this a go :)

**Comment by murezzda** [comment]
@pietrop working on a PR, should be ready next week.

**Comment by pietrop** [comment]
explored in PR #102 but parked for now.
